export const CHANGE_Home_BANNERS = "home/CHANGE_HOME_BANNERS";
export const CHANGE_Home_WORKS = "home/CHANGE_HOME_WORKS";
export const CHANGE_HOME_PAGES = "home/CHANGE_HOME_PAGES";
export const CHANGE_PAGE_TYPES = "home/CHANGE_PAGE_TYPES";
export const CHANGE_WORKS_IMAGES = "home/CHANGE_WORKS_IMAGES";